class Phrases
{
  static Map<String, Map<String, String>> get data => _data;

  static final Map<String, Map<String, String>> _data =
  {
    "en":
    {
      "account" : "account",
      "account_settings" : "account settings",
      "action" : "actions",
      "actions" : "actions",
      "actions_description" : "Actions can be something to do or an event that could be connected to a specific time. Actions are presented in the timeline and learning content can be attached to them.",
      "active" : "active",
      "active_users_count" : "number of active users",
      "actives" : "actives",
      "activity" : "activity",
      "activity_last_30_days" : "activities the last 30 days",
      "add" : "add",
      "add_many" : "add many",
      "add_action" : "add actions",
      "administration" : "administration",
      "advanced" : "advanced",
      "affected_users" : "affected users",
      "affected_users_description" : "If you make changes in an introduction plan, you can here choose which users that should be affected by the changes. Click on a user to change status.",
      "after_first_view" : "after the first view",
      "all" : "all",
      "amount_of" : "amount of",
      "are_you_sure_delete_this_action" : "Are you sure you want to delete this action?",
      "are_you_sure_delete_this_course" : "Are you sure you want to delete this introduction plan?",
      "are_you_sure_delete_this_learning_content" : "Are you sure you want to delete this learning content?",
      "are_you_sure_delete_this_push_notification" : "Are you sure you want to delete this push notification?",
      "are_you_sure_delete_this_resource" : "Are you sure you want to delete this resource?",
      "are_you_sure_delete_this_user" : "Are you sure you want to delete this user?",
      "back" : "back",
      "back_to_editing" : "back to editing",
      "cancel" : "cancel",
      "change_day" : "change day",
      "change_time" : "change time",
      "choose_at_least_one" : "choose at least one",
      "collegues" : "add the colleagues linkedIn profiles",
      "color_highlight" : "highlight",
      "colors" : "colors",
      "color_primary" : "primary color",
      "color_secondary" : "secondary color",
      "completed" : "completed",
      "confirm" : "confirm",
      "confirm_continue" : "yes, continue",
      "confirm_email_sms_valid" : "Double check the contact information:",
      "confirm_renew_password" : "Do you want to generate a new password for the user?",
      "connecteds" : "connected",
      "connected_users" : "connected users",
      "contact_information" : "contact information",
      "contact_us" : "contact us",
      "content" : "content",
      "content_title" : "content title",
      "content_type" : "content type",
      "continue" : "continue",
      "count" : "number",
      "course" : "introduction plan",
      "courses" : "introduction plans",
      "courses_description" : "Introduction plans collect the activities and the learning contents that is shown on the front page.",
      "created" : "created",
      "csv_tooltip" : "Pus semi-colon between the different values and line break between every user - mail@mail.com;070xxxxxxx;first name;surname",
      "custom" : "custom",
      "custom_html" : "custom html",
      "custom_html_description" : "Create a mail with custom formatted html.",
      "date_from" : "date from",
      "date_to" : "date to",
      "day" : "day",
      "days" : "days",
      "days_to_first_day" : "number of days from the first day on the job",
      "delete" : "delete",
      "description" : "description",
      "design" : "design",
      "details" : "details",
      "download_csv" : "export list",
      "download_template" : "download template",
      "edit" : "edit",
      "edit_action" : "edit action",
      "edit_action_on_timeline" : "edit action on the timeline",
      "email" : "email",
      "email_from" : "email from",
      "email_notification_sent" : "email notification sent",
      "email_or_phone_must_be_set" : "mail or mobile number must be set",
      "email_sent" : "email sent",
      "email_template" : "<table bordercolor='#ddd' align='center' cellpadding='10' cellspacing='0' width='600' style='border-collapse:collapse; border:1px solid #ddd; width:600px; text-align:center; font-family: Helvetica, Arial, sans-serif;'><tr><td style='text-align:left;'><img alt='logo' src='https://introduktion.nu/repositories/%client%/logo.png' style='width:300px;'></td></tr><tr><td>%body%</td></tr><tr><td><p style='text-align:center;font-size:0.9em;color:#888'>Do you have questions or comments? Contact us by email: support@introduktion.nu</p></td></tr></table>",
      "embed" : "embed",
      "embedded" : "embedded",
      "embedded_email" : "use default design",
      "embedded_email_description" : "embed the mail message in a default html template, with the company logo in the header.",
      "enter_a_value" : "don't leave this panel empty",
      "enter_alpha_numeric_values_only" : "only letters and numbers are allowed in this panel",
      "enter_at_least_num_letters" : "enter at least one %num% symbols",
      "enter_valid_swedish_cellphone_without_spaces" : "enter a mobile number without spaces (07xxxxxxxx)",
      "error_cant_delete_course_with_connected_users" : "You can't delete this introduction plan, because there are subscribing users.",
      "error_could_not_update_password" : "The user password could not be updated.",
      "error_file_error_413" : "An error occured: The file is too large! (max 10mb)",
      "error_file_in_user_by_learning_contents" : "[%file%] could not be deleted, because it is used in the following learning contents: %learning_contents%",
      "error_http_400" : "Failed request, probably due to an internal error. An automatic bug report has been sent to our support. Please contact us if the error remains.",
      "error_http_401" : "Access denied. Please login again or contact us if the error remains.",
      "error_http_403" : "Access denied, probably due to an internal error. An automatic bug report has been sent to our support. Please contact us if the error remains.",
      "error_http_404" : "Couldn't find the resource.",
      "error_http_405" : "Method not allowed, probably due to an internal error. An automatic bug report has been sent to our support. Please contact us if the error remains.",
      "error_http_409" : "Conflict. This usually occurs when you try to overwrite a unique value for a resource.",
      "error_http_500" : "Internal server error. Please login again or contact us if the error remains.",
      "error_http_502" : "Bad gateway",
      "error_http_503" : "The service is not available at the moment.",
      "error_http_504" : "Gateway timeout",
      "error_mysqli_error_1451" : "This object is protected, because it is connected to other resources. Remove the object from the resources and try again.",
      "error_mysqli_error_1062" : "Kunde inte spara objektet på grund av en unik restriktion i databasen.",
      "error_occurred" : "an error occurred",
      "error_unique_action_name" : "an action with this name already exists.",
      "error_unique_email" : "this email address is already taken by another user.",
      "error_unique_learning_content_name" : "a learning content with this name already exists",
      "error_unique_phone" : "this phonenumber is already taken by another user.",
      "error_unique_push_notification_name" : "a notification with this name already exists.",
      "error_unique_username" : "this username is taken by another user.",
      "error_user_already_registered" : "this user with this username is already registered.",
      "error_user_has_no_contact_info" : "the user has no contact information registered.",
      "error_user_not_found" : "could not find someone with this username.",
      "event" : "event",
      "event_log" : "log",
      "event_reset_password" : "password reset",
      "example" : "example",
      "external_url" : "external URL",
      "failed" : "failed",
      "false" : "false",
      "file" : "file",
      "filename" : "file name",
      "file_manager" : "file manager",
      "files" : "files",
      "files_description" : "Upload and delete your files here. The files can be attached to learning content.",
      "filter" : "filter",
      "firstname" : "first name",
      "firstname_must_be_set" : "first name must be set",
      "first_day_at_work" : "first day",
      "footer_learning_content" : "Learning content in the footer",
      "forgot_password" : "forgot password",
      "forgot_password_description" : "Write your user name to reset your password.",
      "frontpage" : "front page",
      "frontpage_settings" : "front page settings",
      "glassogram_url" : "'glassogram' url",
      "home" : "home",
      "hours" : "hours",
      "hours_before" : "hours before",
      "icon" : "icon",
      "images" : "images",
      "library" : "library",
      "html_example" : "html example",
      "html_example_description" : "<h1>Hi, welcome!</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>",
      "ignore" : "ignore",
      "in_library" : "in the library",
      "in_timeline" : "in the timeline",
      "inactive" : "inactive",
      "include_inactive" : "include inactive",
      "index.html" : "dashboard",
      "information" : "information",
      "invalid_details" : "invalid user name or password",
      "invalid_email" : "invalid email %email%",
      "invalid_file" : "Invalid file format",
      "invalid_file_data" : "could not read the file.",
      "invalid_linkedin_id" : "set a valid linkedIn ID (first name-surname-xxxx)",
      "invalid_phone" : "invalid mobile number %phone%",
      "invalid_token" : "invalid reset token",
      "invalid_url" : "set a valid URL (include http / https)",
      "invalid_youtube_id" : "set a valid Youtube ID (11 digits)",
      "invitation" : "welcome message",
      "instructions" : "instructions",
      "key" : "key",
      "last_30_days" : "the last 30 days",
      "last_login" : "last inlog",
      "lastname" : "surname",
      "lastname_must_be_set" : "surname must be set",
      "learning_content" : "learning content",
      "learning_content_push_notification_description" : "You can add a notification, that will be sent out once the user has opened the learning content.",
      "learning_contents" : "learning content",
      "learning_content_views" : "learning content views",
      "learning_contents_description" : "Learning content can be exteral links, videos, sound files or documents. They can be linked from the web or uploaded directly on introduction.nu. Learning content are presented in the library.", /* TODO lägg till SCORM-paket när funktionen finns */
      "library_learning_contents" : "learning content in the library",
      "list" : "list",
      "location" : "location",
      "logged_in" : "logged in",
      "login" : "login",
      "logins" : "logins",
      "login_details_user_email" : "<div style='font-family: Helvetica, Arial, sans-serif;'><h3 style='text-align:center;'>Your login settings:</h3><table style='margin:0 auto;'><tr><td style='text-align:right;'>User name:</td><td style='text-align:left;'>%username%</td></tr><tr><td style='text-align:right;'>Password:</td><td style='text-align:left;'>%password%</td></tr></table><h4 style='text-align:center; margin-bottom:5px;'>You can also login directly on your profile <a href='https://%client%.introduktion.nu/profile/?token=%token%'>here</a>.</h4><p style='text-align:center; font-size:0.9em; margin-top:5px;'>Is the link not working? Try paste it in your web browser:<br />https://%client%.introduktion.nu/profile/?token=%token%</p></div>",
      "login_details_user_sms" : "\n\nYour inlog settings: %username% / %password%\n\nDirect link: https://%client%.introduktion.nu/profile/?token=%token%",
      "logout" : "logout",
      "logotype" : "logotype",
      "max_filesize_exceeded" : "the maximum filesize has exceeded",
      "menu" : "menu",
      "message" : "message",
      "modules" : "modules",
      "move_all" : "move all",
      "name" : "name",
      "new_password" : "new password",
      "next" : "next",
      "no" : "no",
      "no_actions_found" : "no actions found",
      "no_learning_contents_found" : "no learning content found",
      "no_courses_found" : "no introcuction plans found",
      "no_push_notifications_found" : "no notifications found",
      "no_results" : "no results",
      "no_sms_credits" : "no SMS credits",
      "no_users_found" : "no users found",
      "no_whitespace_allowed" : "no spaces are allowed in this panel",
      "none" : "none",
      "not_started" : "not started",
      "notified" : "notification sent",
      "notify_description" : "You can send a personal welcome message to the user via email and/or SMS. Choose a preset notification from the list or write a new message. A password and a direct link to the user's front page will be added automatically in the end of the message.",
      "notify_email" : "send email",
      "notify_sms" : "send SMS",
      "onboarding_description" : "Mobile personal preboarding. The perfect introduction for your newcomers.",
      "ongoing" : "ongoing",
      "other" : "other",
      "page" : "page",
      "password" : "password",
      "phone" : "mobile number",
      "phrases" : "phrases",
      "pixels" : "pixels",
      "placeholder_description" : "with placeholders you can add dynamic values in your text, e.g. the user name.",
      "placeholders" : "placeholder",
      "preview" : "preview",
      "previous" : "previous",
      "push_notification" : "push notification",
      "push_notifications" : "push notifications",
      "push_notifications_description" : "Push notifications are preset email and/or SMS that can be sent to users. They are primarily used for the welcome messages, but can also be used in other ways.",
      "push_notification_not_qualified" : "Add mobile number or email address to send the notification.",
      "push_sms" : "push SMS",
      "read_more" : "read more",
      "received_invitation" : "received welcome message",
      "received_email" : "received email notification",
      "received_sms" : "received SMS notification",
      "recover_password" : "reset password",
      "recover_password_message_admin_email" : "<h1 style='text-align:center'>Hi!</h1><p style='text-align:center'>To update your password, use the following reset key: <strong>%token%</strong></p><p style='text-align:center; font-size:0.9em;'>If you haven't demanded a reset of your password, you can ignore this message.</p>",
      "recover_password_message_user_sms" : "Your inlog settings: %username% / %password%",
      "recover_password_message_user_email" : "<h1 style='text-align:center'>Hi!</h1><p style='text-align:center'>To update your password, use the following reset key: <strong>%token%</strong><p style='text-align:center; font-size:0.9em;'>If you haven't demanded a reset of your password, you can ignore this message.</p>",
      "recover_password_subject_email" : "reset password",
      "reminder" : "reminder",
      "reminders" : "reminder",
      "remove" : "delete",
      "remove_from_timeline" : "delete from the timeline",
      "reports" : "reports",
      "reset_password" : "reset password",
      "reset_password_description" : "We have sent an email with a reset key to you. Paste it below to update your password.",
      "resource_has_dependencies_leading" : "This object cannot be changed, since the following users subscribe to it:",
      "resource_has_dependencies_trailing" : "Remove the object from the users and try again.",
      "result" : "result",
      "rows" : "rows",
      "save" : "save",
      "search" : "search",
      "select" : "select",
      "select_time" : "select time",
      "send" : "send",
      "sent_smss" : "sent SMS",
      "services" : "services",
      "settings" : "settings",
      "settings_saved" : "The changes have been saved.",
      "size" : "size",
      "size_kb" : "filesize (kb)",
      "sms_credits" : "SMS credits",
      "sms_from" : "SMS from",
      "sms_notification_sent" : "SMS notification sent",
      "sms_sent" : "SMS sent.",
      "shown" : "shown",
      "social_media" : "social media",
      "specify_course" : "the user mus be subscribe to an introduction plan.",
      "specify_email_address" : "set an email address",
      "specify_email_subject" : "the subject panel cannot be empty",
      "specify_message" : "the message panel cannot be empty",
      "specify_phone_number" : "set a phone number",
      "start_date" : "start date",
      "start_videos" : "start videos",
      "start_videos_description" : "Set videos that will be shown at the top of the front page, the first time the user comes in, the second and thereafter. You can add notifications to learning content that will be sent when the video has been shown once.",
      "state" : "state",
      "subject" : "subject",
      "success" : "success",
      "template" : "template",
      "theme" : "theme",
      "time" : "time",
      "timeline" : "timeline",
      "timeline_actions" : "actions on the timeline",
      "timeline_background" : "timeline background",
      "timestamp" : "timestamp",
      "token" : "reset key",
      "true" : "true",
      "type" : "type",
      "unassigned" : "unassigned",
      "unavailable" : "unavailable",
      "unlimited" : "unlimited",
      "undo" : "undo",
      "update" : "update",
      "update_connected_users" : "update subscribing users",
      "upload" : "upload",
      "upload_quota" : "upload quota",
      "url" : "URL",
      "used_space" : "used space",
      "user" : "user",
      "users" : "users",
      "users_description" : "Users are newcomers that can subscribe to a introduction plan. Users can be added one by one or in group.",
      "user_has_no_actions" : "the user doesn't subscribe to any actions",
      "user_has_no_learning_contents" : "the user doesn't subscribe to any learning contents",
      "user_has_been_notified" : "the user has received a welcome message",
      "user_has_not_been_notified" : "the user has not received an welcome message",
      "user_management" : "user management",
      "user_name_not_complete" : "the username must have at least 6 digits.",
      "user_with_email_already_exists" : "the email address %email% is already taken by another user",
      "user_with_username_already_exists" : "the username %username% is already taken by another user",
      "user_with_phone_already_exists" : "the phonenumber %phone% is already taken by another user",
      "username" : "username",
      "video" : "video",
      "viewed_learning_content" : "viewed the learning content",
      "was_created" : "was created",
      "was_deleted" : "was deleted",
      "we_look_forward_to_your_start" : "We look forward to you starting!",
      "welcome" : "welcome",
      "welcome_message" : "welcome message",
      "yes" : "yes",
      "your_first_day_is_in" : "Your first day is in",
      "your_profile" : "your profile",
      "your_timeline" : "your timeline",
      "your_timeline_text" : "Here you find all the actions connected to your introduction."
    }
    "sv":
    {
      "account" : "konto",
      "account_settings" : "kontoinställningar",
      "action" : "aktivitet",
      "actions" : "aktiviteter",
      "actions_description" : "Aktiviteter kan vara något att utföra eller en händelse som kan knytas till en tidpunkt. Aktiviteter presenteras i tidslinjen och lärinnehåll kan kopplas till dem.",
      "active" : "aktiv",
      "active_users_count" : "antal aktiva användare",
      "actives" : "aktiva",
      "activity" : "aktivitet",
      "activity_last_30_days" : "aktivitet senaste 30 dagarna",
      "add" : "lägg till",
      "add_many" : "lägg till flera",
      "add_action" : "lägg till aktivitet",
      "administration" : "administration",
      "advanced" : "avancerat",
      "affected_users" : "påverkade användare",
      "affected_users_description" : "Här kan du ange vilka användare som ska påverkas av eventuella ändringar du gör i introduktionsplanen. Klicka på en användare för att ändra dess status.",
      "after_first_view" : "vid första visning",
      "all" : "alla",
      "amount_of" : "antal",
      "are_you_sure_delete_this_action" : "Är du säker på att du vill ta bort denna aktivitet?",
      "are_you_sure_delete_this_course" : "Är du säker på att du vill ta bort denna introduktionsplan?",
      "are_you_sure_delete_this_learning_content" : "Är du säker på att du vill ta bort detta lärinnehåll?",
      "are_you_sure_delete_this_push_notification" : "Är du säker på att du vill ta bort detta utskick?",
      "are_you_sure_delete_this_resource" : "Är du säker på att du vill ta bort denna resurs?",
      "are_you_sure_delete_this_user" : "Är du säker på att du vill ta bort denna användare?",
      "back" : "tillbaka",
      "back_to_editing" : "tillbaka till redigeringen",
      "cancel" : "avbryt",
      "change_day" : "byt dag",
      "change_time" : "byt tid",
      "choose_at_least_one" : "välj minst ett",
      "collegues" : "lägg till kollegornas linkedIn-profiler",
      "color_highlight" : "highlight",
      "colors" : "färger",
      "color_primary" : "primär",
      "color_secondary" : "sekundär",
      "completed" : "avslutad",
      "confirm" : "bekräfta",
      "confirm_continue" : "ja, fortsätt",
      "confirm_email_sms_valid" : "Dubbelkolla att uppgifterna stämmer:",
      "confirm_renew_password" : "Vill du generera ett nytt lösenord för användaren?",
      "connecteds" : "anslutna",
      "connected_users" : "anslutna användare",
      "contact_information" : "kontaktinformation",
      "contact_us" : "kontakta oss",
      "content" : "innehåll",
      "content_title" : "innehållstitel",
      "content_type" : "innehållstyp",
      "continue" : "fortsätt",
      "count" : "antal",
      "course" : "plan",
      "courses" : "introduktionsplaner",
      "courses_description" : "Introduktionsplaner samlar aktiviteter och lärinnehåll på det sätt som de ska presenteras på portalen för användarna.",
      "created" : "skapad",
      "csv_tooltip" : "Semi-kolon mellan varje värde och radbryt mellan varje användare - mejl@mejl.com;070xxxxxxx;förnamn;efternamn",
      "custom" : "anpassad",
      "custom_html" : "anpassad html",
      "custom_html_description" : "Skapa ett mejl med egenformatterad html.",
      "date_from" : "fr.o.m",
      "date_to" : "t.o.m.",
      "day" : "dag",
      "days" : "dagar",
      "days_to_first_day" : "antal dagar från första dagen på jobbet",
      "delete" : "radera",
      "description" : "beskrivning",
      "design" : "design",
      "details" : "uppgifter",
      "download_csv" : "exporta listan",
      "download_template" : "hämta mall",
      "edit" : "redigera",
      "edit_action" : "redigera aktivitet",
      "edit_action_on_timeline" : "redigera aktivitet på tidslinjen",
      "email" : "mejl",
      "email_from" : "mejlavsändare",
      "email_notification_sent" : "mejl-notifikation skickad",
      "email_or_phone_must_be_set" : "Mejl eller mobil måste vara specificerat",
      "email_sent" : "mejl skickades.",
      "email_template" : "<table bordercolor='#ddd' align='center' cellpadding='10' cellspacing='0' width='600' style='border-collapse:collapse; border:1px solid #ddd; width:600px; text-align:center; font-family: Helvetica, Arial, sans-serif;'><tr><td style='text-align:left;'><img alt='logo' src='https://introduktion.nu/repositories/%client%/logo.png' style='width:300px;'></td></tr><tr><td>%body%</td></tr><tr><td><p style='text-align:center;font-size:0.9em;color:#888'>Har du frågor eller synpunkter? Kontakta oss gärna via mejl: support@introduktion.nu</p></td></tr></table>",
      "embed" : "inbäddad",
      "embedded" : "inbäddad",
      "embedded_email" : "använd standarddesign",
      "embedded_email_description" : "bädda in mejl-meddelandet i en standardiserad html-mall, med företagets logotyp i sidhuvudet.",
      "enter_a_value" : "detta fält får inte vara tomt",
      "enter_alpha_numeric_values_only" : "Endast bokstäver och siffror är tillåtna i detta fält",
      "enter_at_least_num_letters" : "Ange minst %num% tecken",
      "enter_valid_swedish_cellphone_without_spaces" : "Ange ett mobilnummer utan mellanslag (07xxxxxxxx)",
      "error_cant_delete_course_with_connected_users" : "Det går inte att ta bort denna introduktionsplan eftersom den har anslutna användare.",
      "error_could_not_update_password" : "Kunde inte uppdatera användarens lösenord.",
      "error_file_error_413" : "Ett fel inträffade: Filen är för stor! (max 10mb)",
      "error_file_in_user_by_learning_contents" : "[%file%] kunde inte tas bort eftersom den används av följande lärinnehåll: %learning_contents%",
      "error_http_400" : "Felaktig begäran - detta beror förmodligen på ett internt fel. En automatisk felrapport har skickats till vår tekniska support. Kontakta oss gärna om felet kvarstår",
      "error_http_401" : "Behörighet saknas - vänligen logga in igen eller kontakta oss om felet kvarstår",
      "error_http_403" : "Åtkomst nekad - detta beror förmodligen på ett internt fel. En automatisk felrapport har skickats till vår tekniska support. Kontakta oss gärna om felet kvarstår",
      "error_http_404" : "Kunde inte hitta den begärda resursen",
      "error_http_405" : "Felaktig metod - detta beror förmodligen på ett internt fel. En automatisk felrapport har skickats till vår tekniska support. Kontakta oss gärna om felet kvarstår",
      "error_http_409" : "Konflikt - detta sker vanligen när man försöker skriva över ett unikt värde för en resurs",
      "error_http_500" : "Internt serverfel - vänligen försök igen senare eller kontakta oss om felet kvarstår",
      "error_http_502" : "Felaktig gateway",
      "error_http_503" : "Tjänsten är inte tillgänglig för tillfället",
      "error_http_504" : "Gateway timeout",
      "error_mysqli_error_1451" : "Detta objekt är skrivskyddat eftersom det är kopplat till andra resurser. Plocka bort det från de andra resurserna och försök igen.",
      "error_mysqli_error_1062" : "Kunde inte spara objektet på grund av en unik restriktion i databasen.",
      "error_occurred" : "ett fel inträffade",
      "error_unique_action_name" : "det finns redan en aktivitet med detta namn",
      "error_unique_email" : "det finns redan en användare med denna mejl",
      "error_unique_learning_content_name" : "det finns redan ett lärinnehåll med detta namn",
      "error_unique_phone" : "det finns redan en användare med detta telefonnummer",
      "error_unique_push_notification_name" : "det finns redan ett utskick med detta namn",
      "error_unique_username" : "det finns redan en användare med detta användarnamn",
      "error_user_already_registered" : "Det finns redan en användare med detta användarnamn.",
      "error_user_has_no_contact_info" : "Användaren har inga registrerade kontaktuppgifter",
      "error_user_not_found" : "Kunde inte hitta någon med detta användarnamn",
      "event" : "händelse",
      "event_log" : "logg",
      "event_reset_password" : "återställde lösenord",
      "example" : "exempel",
      "external_url" : "extern URL",
      "failed" : "misslyckades",
      "false" : "falskt",
      "file" : "fil",
      "filename" : "filnamn",
      "file_manager" : "filhanterare",
      "files" : "filer",
      "files_description" : "Här kan ladda upp och ta bort filer. Filerna kan användas när du skapar lärinnehåll.",
      "filter" : "filtrera",
      "firstname" : "förnamn",
      "firstname_must_be_set" : "förnamn får inte vara tomt",
      "first_day_at_work" : "första dagen",
      "footer_learning_content" : "Lärinnehåll i sidfot",
      "forgot_password" : "glömt lösenord",
      "forgot_password_description" : "Skriv in ditt användarnamn för att återställa ditt lösenord.",
      "frontpage" : "portal",
      "frontpage_settings" : "portaldesign",
      "glassogram_url" : "glassogram-url",
      "home" : "hem",
      "hours" : "timmar",
      "hours_before" : "timmar innan",
      "icon" : "ikon",
      "images" : "bilder",
      "library" : "bibliotek",
      "html_example" : "Html-exempel",
      "html_example_description" : "<h1>Hej och välkommen!</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>",
      "ignore" : "ignorera",
      "in_library" : "i bibliotek",
      "in_timeline" : "i tidslinjen",
      "inactive" : "inaktiv",
      "include_inactive" : "inkludera inaktiva",
      "index.html" : "dashboard",
      "information" : "information",
      "invalid_details" : "felaktigt användarnamn eller lösenord",
      "invalid_email" : "felaktig e-post %email%",
      "invalid_file" : "Felaktigt filformat",
      "invalid_file_data" : "Kunde inte läsa in filen",
      "invalid_linkedin_id" : "Ange ett giltigt LinkedIn-ID (fornamn-efternamn-xxxx)",
      "invalid_phone" : "felaktigt mobilnummer %phone%",
      "invalid_token" : "felaktig återställningsnyckel",
      "invalid_url" : "Ange en giltig URL (inklusive http / https)",
      "invalid_youtube_id" : "Ange ett giltigt Youtube-ID (11 tecken)",
      "invitation" : "inbjudan",
      "instructions" : "instruktioner",
      "key" : "nyckel",
      "last_30_days" : "senaste 30 dagarna",
      "last_login" : "senast inloggad",
      "lastname" : "efternamn",
      "lastname_must_be_set" : "efternamn får inte vara tomt",
      "learning_content" : "lärinnehåll",
      "learning_content_push_notification_description" : "Här kan välja att göra ett utskick till användaren som skickas efter att denne tagit del av lärinnehållet.",
      "learning_contents" : "lärinnehåll",
      "learning_content_views" : "Visade lärinnehåll",
      "learning_contents_description" : "Lärinnehåll kan vara externa länkar, filmer, ljudfiler eller dokument. Det kan hämtas via webblänkar eller från uppladdade filer på introduktion.nu. Lärinnehåll presenteras i biblioteket.", /* TODO lägg till SCORM-paket när funktionen finns */
      "library_learning_contents" : "lärinnehåll i bibliotek",
      "list" : "lista",
      "location" : "plats",
      "logged_in" : "loggade in",
      "login" : "logga in",
      "logins" : "inloggningar",
      "login_details_user_email" : "<div style='font-family: Helvetica, Arial, sans-serif;'><h3 style='text-align:center;'>Dina inloggningsuppgifter:</h3><table style='margin:0 auto;'><tr><td style='text-align:right;'>Användarnamn:</td><td style='text-align:left;'>%username%</td></tr><tr><td style='text-align:right;'>Lösenord:</td><td style='text-align:left;'>%password%</td></tr></table><h4 style='text-align:center; margin-bottom:5px;'>Du kan även logga in direkt på din profil <a href='https://%client%.introduktion.nu/profile/?token=%token%'>här</a>.</h4><p style='text-align:center; font-size:0.9em; margin-top:5px;'>Fungerar inte länken? Prova att klistra in den i din webbläsare:<br />https://%client%.introduktion.nu/profile/?token=%token%</p></div>",
      "login_details_user_sms" : "\n\nDina inloggningsuppgifter: %username% / %password%\n\nDirektlänk: https://%client%.introduktion.nu/profile/?token=%token%",
      "logout" : "logga ut",
      "logotype" : "logotyp",
      "max_filesize_exceeded" : "den maximala filstorleken har överskridits",
      "menu" : "meny",
      "message" : "meddelande",
      "modules" : "moduler",
      "move_all" : "flytta alla",
      "name" : "namn",
      "new_password" : "nytt lösenord",
      "next" : "nästa",
      "no" : "nej",
      "no_actions_found" : "Inga aktiviteter funna",
      "no_learning_contents_found" : "Inga lärinnehåll funna",
      "no_courses_found" : "Inga introduktionsplaner funna",
      "no_push_notifications_found" : "Inga utskick funna",
      "no_results" : "inga resultat",
      "no_sms_credits" : "SMS-krediter saknas",
      "no_users_found" : "Inga användare funna",
      "no_whitespace_allowed" : "detta fält får inte innehålla mellanslag",
      "none" : "ingen",
      "not_started" : "ej startat",
      "notified" : "inbjudan skickad",
      "notify_description" : "Här kan du skicka en inbjudan till användaren via mejl och/eller sms med valfritt meddelande. Välj ett utskick nedan eller skriv ett helt anpassat meddelande. Ett nytt lösenord och en direktlänk till användarens profil kommer automatiskt att läggas till i slutet av meddelandet.",
      "notify_email" : "skicka mejl",
      "notify_sms" : "skicka SMS",
      "onboarding_description" : "Mobil anpassningsbar preboarding. Innehållspaket och systemstöd för en enkel, kul och effektiv introduktion av nyanställda.",
      "ongoing" : "pågående",
      "other" : "övrigt",
      "page" : "sida",
      "password" : "lösenord",
      "phone" : "mobilnummer",
      "phrases" : "texter",
      "pixels" : "pixlar",
      "placeholder_description" : "med platshållare kan du lägga till dynamiska värden i meddelandet, exempelvis användarens namn.",
      "placeholders" : "platshållare",
      "preview" : "förhansgranska",
      "previous" : "föregående",
      "push_notification" : "utskick",
      "push_notifications" : "utskick",
      "push_notifications_description" : "Utskick är fördefinierade mejl och/eller sms som kan skickas ut till användare. Utskick används i första hand som inbjudan till portalen, men kan även skickas vid andra tillfällen.",
      "push_notification_not_qualified" : "Fyll i mobilnummer eller mejl för att göra utskick",
      "push_sms" : "push-SMS",
      "read_more" : "läs mer",
      "received_invitation" : "fick inbjudan",
      "received_email" : "fick mejl-utskick",
      "received_sms" : "fick SMS-utskick",
      "recover_password" : "Återställning lösenord introduktion.nu",
      "recover_password_message_admin_email" : "<h1 style='text-align:center'>Hej!</h1><p style='text-align:center'>För att uppdatera ditt lösenord på introduktion.nu, använd följande återställningsnyckel: <strong>%token%</strong></p><p style='text-align:center; font-size:0.9em;'>Om du inte begärt att återställa ditt lösenord kan du ignorera detta meddelande.</p>",
      "recover_password_message_user_sms" : "Dina inloggningsuppgifter: %username% / %password%",
      "recover_password_message_user_email" : "<h1 style='text-align:center'>Hej!</h1><p style='text-align:center'>För att uppdatera ditt lösenord på introduktion.nu, använd följande återställningsnyckel: <strong>%token%</strong><p style='text-align:center; font-size:0.9em;'>Om du inte begärt att återställa ditt lösenord kan du ignorera detta meddelande.</p>",
      "recover_password_subject_email" : "Återställ lösenord",
      "reminder" : "påminnelse",
      "reminders" : "påminnelser",
      "remove" : "ta bort",
      "remove_from_timeline" : "ta bort från tidslinjen",
      "reports" : "rapporter",
      "reset_password" : "återställ lösenord",
      "reset_password_description" : "Vi har skickat ett mejl till dig med en återställningsnyckel, klistra in den nedan för att uppdatera ditt lösenord.",
      "resource_has_dependencies_leading" : "Detta objekt är skrivskyddat eftersom det är kopplat till följande resurser:",
      "resource_has_dependencies_trailing" : "Plocka bort objektet från de berörda resurserna och försök igen.",
      "result" : "resultat",
      "rows" : "rader",
      "save" : "spara",
      "search" : "sök",
      "select" : "välj",
      "select_time" : "välj tid",
      "send" : "skicka",
      "sent_smss" : "skickade sms",
      "services" : "tjänster",
      "settings" : "inställningar",
      "settings_saved" : "Ändringarna har sparats.",
      "size" : "storlek",
      "size_kb" : "filstorlek (kb)",
      "sms_credits" : "SMS-krediter",
      "sms_from" : "SMS-avsändare",
      "sms_notification_sent" : "SMS-notifikation skickad",
      "sms_sent" : "SMS skickades.",
      "shown" : "visat",
      "social_media" : "sociala medier",
      "specify_course" : "användaren måste vara registrerad på en introduktionsplan",
      "specify_email_address" : "ange en mejladress",
      "specify_email_subject" : "ämnestitel får inte vara tom",
      "specify_message" : "meddelandefältet får inte vara tomt",
      "specify_phone_number" : "ange ett telefonnummer",
      "start_date" : "startdatum",
      "start_videos" : "startfilmer",
      "start_videos_description" : "Här anger du vilka filmer som visas längst upp på portalsidan, i turordning. Om du lagt till ett utskick på lärinnehållet skickas detta efter att filmen har visats första gången.",
      "state" : "stadie",
      "subject" : "ämnestitel",
      "success" : "lyckades",
      "template" : "mall",
      "theme" : "tema",
      "time" : "klockan",
      "timeline" : "tidslinje",
      "timeline_actions" : "aktiviteter på tidslinjen",
      "timeline_background" : "bakgrund tidslinje",
      "timestamp" : "tidpunkt",
      "token" : "återställningsnyckel",
      "true" : "sant",
      "type" : "typ",
      "unassigned" : "ej tilldelad",
      "unavailable" : "ej tillgängligt",
      "unlimited" : "obegränsat",
      "undo" : "ångra",
      "update" : "uppdatera",
      "update_connected_users" : "uppdatera anslutna användare",
      "upload" : "ladda upp",
      "upload_quota" : "uppladdningskvot",
      "url" : "URL",
      "used_space" : "utnyttjat utrymme",
      "user" : "användare",
      "users" : "användare",
      "users_description" : "Användare är nyanställda som har en introduktionsplan kopplad till sig. Användare kan läggas upp en och en eller i grupp.",
      "user_has_no_actions" : "användaren har inga kopplade aktiviteter",
      "user_has_no_learning_contents" : "användaren har inga kopplade lärinnehåll",
      "user_has_been_notified" : "användaren fick en inbjudan",
      "user_has_not_been_notified" : "användaren har inte fått någon inbjudan",
      "user_management" : "användarhantering",
      "user_name_not_complete" : "Användarnamnet måste ha minst 6 bokstäver.",
      "user_with_email_already_exists" : "det finns redan en användare med epost: %email%",
      "user_with_username_already_exists" : "det finns redan en användare med användarnamn: %username%",
      "user_with_phone_already_exists" : "det finns redan en användare med telefonnummer: %phone%",
      "username" : "användarnamn",
      "video" : "film",
      "viewed_learning_content" : "tog del av lärinnehåll",
      "was_created" : "skapades",
      "was_deleted" : "raderades",
      "we_look_forward_to_your_start" : "Vi ser fram emot att du ska börja!",
      "welcome" : "välkommen",
      "welcome_message" : "inbjudan",
      "yes" : "ja",
      "your_first_day_is_in" : "Din första dag hos oss är om",
      "your_profile" : "din profil",
      "your_timeline" : "din tidslinje",
      "your_timeline_text" : "Här hittar du de aktiviteter som rör din introduktion."
    }
  };
}
