class Phrases
{
  static Map<String, Map<String, String>> get data => _data;

  static final Map<String, Map<String, String>> _data =
  {
    "sv":
    {
      "account" : "konto",
      "account_settings" : "kontoinställningar",
      "action" : "aktivitet",
      "actions" : "aktiviteter",
      "actions_description" : "Aktiviteter kan vara något att utföra eller en händelse som kan knytas till en tidpunkt. Aktiviteter presenteras i tidslinjen och lärinnehåll kan kopplas till dem.",
      "active" : "aktiv",
      "active_users_count" : "antal aktiva användare",
      "actives" : "aktiva",
      "activity" : "aktivitet",
      "activity_last_30_days" : "aktivitet senaste 30 dagarna",
      "add" : "lägg till",
      "add_many" : "lägg till flera",
      "add_action" : "lägg till aktivitet",
      "administration" : "administration",
      "advanced" : "avancerat",
      "affected_users" : "påverkade användare",
      "affected_users_description" : "Här kan du ange vilka användare som ska påverkas av eventuella ändringar du gör i introduktionsplanen. Klicka på en användare för att ändra dess status.",
      "after_first_view" : "vid första visning",
      "all" : "alla",
      "amount_of" : "antal",
      "are_you_sure_delete_this_action" : "Är du säker på att du vill ta bort denna aktivitet?",
      "are_you_sure_delete_this_course" : "Är du säker på att du vill ta bort denna introduktionsplan?",
      "are_you_sure_delete_this_learning_content" : "Är du säker på att du vill ta bort detta lärinnehåll?",
      "are_you_sure_delete_this_push_notification" : "Är du säker på att du vill ta bort detta utskick?",
      "are_you_sure_delete_this_resource" : "Är du säker på att du vill ta bort denna resurs?",
      "are_you_sure_delete_this_user" : "Är du säker på att du vill ta bort denna användare?",
      "back" : "tillbaka",
      "back_to_editing" : "tillbaka till redigeringen",
      "cancel" : "avbryt",
      "change_day" : "byt dag",
      "change_time" : "byt tid",
      "choose_at_least_one" : "välj minst ett",
      "collegues" : "lägg till kollegornas linkedIn-profiler",
      "color_highlight" : "highlight",
      "colors" : "färger",
      "color_primary" : "primär",
      "color_secondary" : "sekundär",
      "completed" : "avslutad",
      "confirm" : "bekräfta",
      "confirm_continue" : "ja, fortsätt",
      "confirm_email_sms_valid" : "Dubbelkolla att uppgifterna stämmer:",
      "confirm_renew_password" : "Vill du generera ett nytt lösenord för användaren?",
      "connecteds" : "anslutna",
      "connected_users" : "anslutna användare",
      "contact_information" : "kontaktinformation",
      "contact_us" : "kontakta oss",
      "content" : "innehåll",
      "content_title" : "innehållstitel",
      "content_type" : "innehållstyp",
      "continue" : "fortsätt",
      "count" : "antal",
      "course" : "plan",
      "courses" : "introduktionsplaner",
      "courses_description" : "Introduktionsplaner samlar aktiviteter och lärinnehåll på det sätt som de ska presenteras på portalen för användarna.",
      "created" : "skapad",
      "csv_tooltip" : "Semi-kolon mellan varje värde och radbryt mellan varje användare - mejl@mejl.com;070xxxxxxx;förnamn;efternamn",
      "custom" : "anpassad",
      "custom_html" : "anpassad html",
      "custom_html_description" : "Skapa ett mejl med egenformatterad html.",
      "date_from" : "fr.o.m",
      "date_to" : "t.o.m.",
      "day" : "dag",
      "days" : "dagar",
      "days_to_first_day" : "antal dagar från första dagen på jobbet",
      "delete" : "radera",
      "description" : "beskrivning",
      "design" : "design",
      "details" : "uppgifter",
      "download_csv" : "exporta listan",
      "download_template" : "hämta mall",
      "edit" : "redigera",
      "edit_action" : "redigera aktivitet",
      "edit_action_on_timeline" : "redigera aktivitet på tidslinjen",
      "email" : "mejl",
      "email_notification_sent" : "mejl-notifikation skickad",
      "email_or_phone_must_be_set" : "Mejl eller mobil måste vara specificerat",
      "email_sent" : "mejl skickades.",
      "email_template" : "<table bordercolor='#ddd' align='center' cellpadding='10' cellspacing='0' width='600' style='border-collapse:collapse; border:1px solid #ddd; width:600px; text-align:center; font-family: Helvetica, Arial, sans-serif;'><tr><td style='text-align:left;'><img alt='logo' src='https://introduktion.nu/repositories/%client%/logo.png' style='width:300px;'></td></tr><tr><td>%body%</td></tr><tr><td><p style='text-align:center;font-size:0.9em;color:#888'>Har du frågor eller synpunkter? Kontakta oss gärna via mejl: support@introduktion.nu</p></td></tr></table>",
      "embed" : "inbäddad",
      "embedded" : "inbäddad",
      "embedded_email" : "använd standarddesign",
      "embedded_email_description" : "bädda in mejl-meddelandet i en standardiserad html-mall, med företagets logotyp i sidhuvudet.",
      "enter_a_value" : "detta fält får inte vara tomt",
      "enter_alpha_numeric_values_only" : "Endast bokstäver och siffror är tillåtna i detta fält",
      "enter_at_least_num_letters" : "Ange minst %num% tecken",
      "enter_valid_swedish_cellphone_without_spaces" : "Ange ett mobilnummer utan mellanslag (07xxxxxxxx)",
      "error_cant_delete_course_with_connected_users" : "Det går inte att ta bort denna introduktionsplan eftersom den har anslutna användare.",
      "error_could_not_update_password" : "Kunde inte uppdatera användarens lösenord.",
      "error_file_error_413" : "Ett fel inträffade: Filen är för stor! (max 10mb)",
      "error_file_in_user_by_learning_contents" : "[%file%] kunde inte tas bort eftersom den används av följande lärinnehåll: %learning_contents%",
      "error_http_400" : "Felaktig begäran - detta beror förmodligen på ett internt fel. En automatisk felrapport har skickats till vår tekniska support. Kontakta oss gärna om felet kvarstår",
      "error_http_401" : "Behörighet saknas - vänligen logga in igen eller kontakta oss om felet kvarstår",
      "error_http_403" : "Åtkomst nekad - detta beror förmodligen på ett internt fel. En automatisk felrapport har skickats till vår tekniska support. Kontakta oss gärna om felet kvarstår",
      "error_http_404" : "Kunde inte hitta den begärda resursen",
      "error_http_405" : "Felaktig metod - detta beror förmodligen på ett internt fel. En automatisk felrapport har skickats till vår tekniska support. Kontakta oss gärna om felet kvarstår",
      "error_http_409" : "Konflikt - detta sker vanligen när man försöker skriva över ett unikt värde för en resurs",
      "error_http_500" : "Internt serverfel - vänligen försök igen senare eller kontakta oss om felet kvarstår",
      "error_http_502" : "Felaktig gateway",
      "error_http_503" : "Tjänsten är inte tillgänglig för tillfället",
      "error_http_504" : "Gateway timeout",
      "error_mysqli_error_1451" : "Operationen kunde inte genomföras eftersom resursen är skrivskyddad. Detta beror vanligtvis på att resursen används av en annan resurs.",
      "error_mysqli_error_1062" : "Kunde inte spara objektet på grund av en unik restriktion i databasen.",
      "error_occurred" : "ett fel inträffade",
      "error_unique_action_name" : "det finns redan en aktivitet med detta namn",
      "error_unique_email" : "det finns redan en användare med denna mejl",
      "error_unique_learning_content_name" : "det finns redan ett lärinnehåll med detta namn",
      "error_unique_phone" : "det finns redan en användare med detta telefonnummer",
      "error_unique_push_notification_name" : "det finns redan ett utskick med detta namn",
      "error_unique_username" : "det finns redan en användare med detta användarnamn",
      "error_user_already_registered" : "Det finns redan en användare med detta användarnamn.",
      "error_user_has_no_contact_info" : "Användaren har inga registrerade kontaktuppgifter",
      "error_user_not_found" : "Kunde inte hitta någon med detta användarnamn",
      "event" : "händelse",
      "event_log" : "logg",
      "event_reset_password" : "återställde lösenord",
      "example" : "exempel",
      "external_url" : "extern URL",
      "failed" : "misslyckades",
      "false" : "falskt",
      "file" : "fil",
      "filename" : "filnamn",
      "file_manager" : "filhanterare",
      "files" : "filer",
      "files_description" : "Här kan ladda upp och ta bort filer. Filerna kan användas när du skapar lärinnehåll.",
      "filter" : "filtrera",
      "firstname" : "förnamn",
      "firstname_must_be_set" : "förnamn får inte vara tomt",
      "first_day_at_work" : "första dagen",
      "footer_learning_content" : "Lärinnehåll i sidfot",
      "forgot_password" : "glömt lösenord",
      "forgot_password_description" : "Skriv in ditt användarnamn för att återställa ditt lösenord.",
      "frontpage" : "portal",
      "frontpage_settings" : "portaldesign",
      "glassogram_url" : "glassogram-url",
      "home" : "hem",
      "icon" : "ikon",
      "images" : "bilder",
      "library" : "bibliotek",
      "html_example" : "Html-exempel",
      "html_example_description" : "<h1>Hej och välkommen!</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>",
      "ignore" : "ignorera",
      "in_library" : "i bibliotek",
      "in_timeline" : "i tidslinjen",
      "inactive" : "inaktiv",
      "include_inactive" : "inkludera inaktiva",
      "index.html" : "dashboard",
      "information" : "information",
      "invalid_details" : "felaktigt användarnamn eller lösenord",
      "invalid_email" : "felaktig e-post %email%",
      "invalid_file" : "Felaktigt filformat",
      "invalid_file_data" : "Kunde inte läsa in filen",
      "invalid_linkedin_id" : "Ange ett giltigt LinkedIn-ID (fornamn-efternamn-xxxx)",
      "invalid_phone" : "felaktigt mobilnummer %phone%",
      "invalid_token" : "felaktig återställningsnyckel",
      "invalid_url" : "Ange en giltig URL (inklusive http / https)",
      "invalid_youtube_id" : "Ange ett giltigt Youtube-ID (11 tecken)",
      "invitation" : "inbjudan",
      "key" : "nyckel",
      "last_30_days" : "senaste 30 dagarna",
      "last_login" : "senast inloggad",
      "lastname" : "efternamn",
      "lastname_must_be_set" : "efternamn får inte vara tomt",
      "learning_content" : "lärinnehåll",
      "learning_content_push_notification_description" : "Här kan välja att göra ett utskick till användaren som skickas efter att denne tagit del av lärinnehållet.",
      "learning_contents" : "lärinnehåll",
      "learning_content_views" : "Visade lärinnehåll",
      "learning_contents_description" : "Lärinnehåll kan vara externa länkar, filmer, ljudfiler eller dokument. Det kan hämtas via webblänkar eller från uppladdade filer på introduktion.nu. Lärinnehåll presenteras i biblioteket.", /* TODO lägg till SCORM-paket när funktionen finns */
      "library_learning_contents" : "lärinnehåll i bibliotek",
      "list" : "lista",
      "location" : "plats",
      "logged_in" : "loggade in",
      "login" : "logga in",
      "logins" : "inloggningar",
      "login_details_user_email" : "<div style='font-family: Helvetica, Arial, sans-serif;'><h3 style='text-align:center;'>Dina inloggningsuppgifter:</h3><table style='margin:0 auto;'><tr><td style='text-align:right;'>Användarnamn:</td><td style='text-align:left;'>%username%</td></tr><tr><td style='text-align:right;'>Lösenord:</td><td style='text-align:left;'>%password%</td></tr></table><h4 style='text-align:center; margin-bottom:5px;'>Du kan även logga in direkt på din profil <a href='https://%client%.introduktion.nu/profile/?token=%token%'>här</a>.</h4><p style='text-align:center; font-size:0.9em; margin-top:5px;'>Fungerar inte länken? Prova att klistra in den i din webbläsare:<br />https://%client%.introduktion.nu/profile/?token=%token%</p></div>",
      "login_details_user_sms" : "\n\nDina inloggningsuppgifter: %username% / %password%\n\nDirektlänk: https://%client%.introduktion.nu/profile/?token=%token%",
      "logout" : "logga ut",
      "logotype" : "logotyp",
      "max_filesize_exceeded" : "den maximala filstorleken har överskridits",
      "menu" : "meny",
      "message" : "meddelande",
      "modules" : "moduler",
      "move_all" : "flytta alla",
      "name" : "namn",
      "new_password" : "nytt lösenord",
      "next" : "nästa",
      "no" : "nej",
      "no_actions_found" : "Inga aktiviteter funna",
      "no_learning_contents_found" : "Inga lärinnehåll funna",
      "no_courses_found" : "Inga introduktionsplaner funna",
      "no_push_notifications_found" : "Inga utskick funna",
      "no_results" : "inga resultat",
      "no_sms_credits" : "SMS-krediter saknas",
      "no_users_found" : "Inga användare funna",
      "no_whitespace_allowed" : "detta fält får inte innehålla mellanslag",
      "none" : "ingen",
      "not_started" : "ej startat",
      "notified" : "inbjudan skickad",
      "notify_description" : "Här kan du skicka en inbjudan till användaren via mejl och/eller sms med valfritt meddelande. Välj ett utskick nedan eller skriv ett helt anpassat meddelande. Ett nytt lösenord och en direktlänk till användarens profil kommer automatiskt att läggas till i slutet av meddelandet.",
      "notify_email" : "skicka mejl",
      "notify_sms" : "skicka SMS",
      "onboarding_description" : "Mobil anpassningsbar preboarding. Innehållspaket och systemstöd för en enkel, kul och effektiv introduktion av nyanställda.",
      "ongoing" : "pågående",
      "other" : "övrigt",
      "page" : "sida",
      "password" : "lösenord",
      "phone" : "mobilnummer",
      "phrases" : "texter",
      "pixels" : "pixlar",
      "placeholder_description" : "med platshållare kan du lägga till dynamiska värden i meddelandet, exempelvis användarens namn.",
      "placeholders" : "platshållare",
      "preview" : "förhansgranska",
      "previous" : "föregående",
      "push_notification" : "utskick",
      "push_notifications" : "utskick",
      "push_notifications_description" : "Utskick är fördefinierade mejl och/eller sms som kan skickas ut till användare. Utskick används i första hand som inbjudan till portalen, men kan även skickas vid andra tillfällen.",
      "push_notification_not_qualified" : "Fyll i mobilnummer eller mejl för att göra utskick",
      "push_sms" : "push-SMS",
      "read_more" : "läs mer",
      "received_invitation" : "fick inbjudan",
      "received_email" : "fick mejl-utskick",
      "received_sms" : "fick SMS-utskick",
      "recover_password" : "Återställning lösenord introduktion.nu",
      "recover_password_message_admin_email" : "<h1 style='text-align:center'>Hej!</h1><p style='text-align:center'>För att uppdatera ditt lösenord på introduktion.nu, använd följande återställningsnyckel: <strong>%token%</strong></p><p style='text-align:center; font-size:0.9em;'>Om du inte begärt att återställa ditt lösenord kan du ignorera detta meddelande.</p>",
      "recover_password_messsage_user_sms" : "Dina inloggningsuppgifter: %username% / %password%",
      "recover_password_message_user_email" : "<h1 style='text-align:center'>Hej!</h1><p style='text-align:center'>För att uppdatera ditt lösenord på introduktion.nu, använd följande återställningsnyckel: <strong>%token%</strong><p style='text-align:center; font-size:0.9em;'>Om du inte begärt att återställa ditt lösenord kan du ignorera detta meddelande.</p>",
      "recover_password_subject_email" : "Återställ lösenord",
      "remove" : "ta bort",
      "remove_from_timeline" : "ta bort från tidslinjen",
      "reports" : "rapporter",
      "reset_password" : "återställ lösenord",
      "reset_password_description" : "Vi har skickat ett mejl till dig med en återställningsnyckel, klistra in den nedan för att uppdatera ditt lösenord.",
      "result" : "resultat",
      "rows" : "rader",
      "save" : "spara",
      "search" : "sök",
      "select" : "välj",
      "select_time" : "välj tid",
      "send" : "skicka",
      "sent_smss" : "skickade sms",
      "services" : "tjänster",
      "settings" : "inställningar",
      "settings_saved" : "Ändringarna har sparats.",
      "size" : "storlek",
      "size_kb" : "filstorlek (kb)",
      "sms_credits" : "SMS-krediter",
      "sms_notification_sent" : "SMS-notifikation skickad",
      "sms_sent" : "SMS skickades.",
      "shown" : "visat",
      "social_media" : "sociala medier",
      "specify_course" : "användaren måste vara registrerad på en introduktionsplan",
      "specify_email_address" : "ange en mejladdress",
      "specify_email_subject" : "ämnestitel får inte vara tom",
      "specify_message" : "meddelandefältet får inte vara tomt",
      "specify_phone_number" : "ange ett telefonnummer",
      "start_date" : "startdatum",
      "start_videos" : "startfilmer",
      "start_videos_description" : "Här anger du vilka filmer som visas längst upp på portalsidan, i turordning. Om du lagt till ett utskick på lärinnehållet skickas detta efter att filmen har visats första gången.",
      "state" : "stadie",
      "subject" : "ämnestitel",
      "success" : "lyckades",
      "template" : "mall",
      "theme" : "tema",
      "time" : "klockan",
      "timeline" : "tidslinje",
      "timeline_actions" : "aktiviteter på tidslinjen",
      "timeline_background" : "bakgrund tidslinje",
      "timestamp" : "tidpunkt",
      "token" : "återställningsnyckel",
      "true" : "sant",
      "type" : "typ",
      "unassigned" : "ej tilldelad",
      "unavailable" : "ej tillgängligt",
      "unlimited" : "obegränsat",
      "undo" : "ångra",
      "update" : "uppdatera",
      "update_connected_users" : "uppdatera anslutna användare",
      "upload" : "ladda upp",
      "upload_quota" : "uppladdningskvot",
      "url" : "URL",
      "used_space" : "utnyttjat utrymme",
      "user" : "användare",
      "users" : "användare",
      "users_description" : "Användare är nyanställda som har en introduktionsplan kopplad till sig. Användare kan läggas upp en och en eller i grupp.",
      "user_has_no_actions" : "användaren har inga kopplade aktiviteter",
      "user_has_no_learning_contents" : "användaren har inga kopplade lärinnehåll",
      "user_has_been_notified" : "användaren fick en inbjudan",
      "user_has_not_been_notified" : "användaren har inte fått någon inbjudan",
      "user_management" : "användarhantering",
      "user_name_not_complete" : "Användarnamnet måste ha minst 6 bokstäver.",
      "user_with_email_already_exists" : "det finns redan en användare med epost: %email%",
      "user_with_username_already_exists" : "det finns redan en användare med användarnamn: %username%",
      "user_with_phone_already_exists" : "det finns redan en användare med telefonnummer: %phone%",
      "username" : "användarnamn",
      "video" : "film",
      "viewed_learning_content" : "tog del av lärinnehåll",
      "was_created" : "skapades",
      "was_deleted" : "raderades",
      "we_look_forward_to_your_start" : "Vi ser fram emot att du ska börja!",
      "welcome" : "välkommen",
      "welcome_message" : "inbjudan",
      "yes" : "ja",
      "your_first_day_is_in" : "Din första dag hos oss är om",
      "your_profile" : "din profil",
    }
  };
}
