class Phrases
{
  static Map<String, Map<String, String>> get data => _data;

  static final Map<String, Map<String, String>> _data =
  {
    "sv":
    {
      "account" : "konto",
      "account_settings" : "kontoinställningar",
      "action" : "aktivitet",
      "action_plural" : "aktiviteter",
      "actions" : "aktiviteter",
      "active" : "aktiv",
      "add" : "lägg till",
      "add_many" : "lägg till flera",
      "add_action" : "lägg till aktivitet",
      "administration" : "administration",
      "advanced" : "avancerat",
      "after_first_view" : "efter första visning",
      "all" : "alla",
      "back" : "tillbaka",
      "back_to_editing" : "tillbaka till redigeringen",
      "cancel" : "avbryt",
      "change_day" : "byt dag",
      "change_time" : "byt tid",
      "choose_at_least_one" : "välj minst ett",
      "color_highlight" : "highlight",
      "color_plural" : "färger",
      "color_primary" : "primär",
      "color_secondary" : "sekundär",
      "confirm" : "bekräfta",
      "confirm_continue" : "ja, fortsätt",
      "confirm_email_sms_valid" : "Dubbelkolla att mejladressen och/eller mobilnumret stämmer:",
      "confirm_email_sms_valid_no_values" : "Du har inte angett mejladdress/mobilnummer, användaren kommer inte att få några inloggningsuppgifter skickade till sig. Är du säker på att du vill fortsätta?",
      "connected_plural" : "anslutna",
      "connected_users" : "anslutna användare",
      "contact_information" : "kontaktinformation",
      "contact_us" : "kontakta oss",
      "content" : "innehåll",
      "content_title" : "innehållstitel",
      "content_type" : "innehållstyp",
      "continue" : "fortsätt",
      "course" : "plan",
      "course_plural" : "introduktionsplaner",
      "courses" : "introduktionsplaner",
      "created" : "skapad",
      "csv_tooltip" : "Semi-kolon mellan varje värde och radbryt mellan varje användare - mejl@mejl.com;070xxxxxxx;förnamn;efternamn",
      "custom" : "anpassad",
      "date_from" : "fr.o.m",
      "date_to" : "t.o.m.",
      "day" : "dag",
      "day_plural" : "dagar",
      "days_to_first_day" : "antal dagar från första dagen på jobbet",
      "delete" : "radera",
      "description" : "beskrivning",
      "design" : "design",
      "details" : "uppgifter",
      "download_csv" : "ladda ned CSV-fil",
      "download_template" : "hämta mall",
      "edit" : "redigera",
      "edit_action" : "redigera aktivitet",
      "edit_action_on_timeline" : "redigera aktivitet på tidslinjen",
      "email" : "mejl",
      "email_embedded_description" : "bädda in mejl-meddelandet i en standardiserad html-mall, med företagets logotyp i sidhuvudet.",
      "email_notification_sent" : "mejl-notifikation skickad",
      "email_sent" : "mejl skickades.",
      "email_template_footer" : "Har du frågor eller synpunkter? Kontakta oss gärna via mejl: support@introduktion.nu",
      "embed" : "inbäddad",
      "embedded" : "inbäddad",
      "embedded_email" : "använd standarddesign",
      "error_occurred" : "ett fel inträffade",
      "error_unique_action_name" : "det finns redan en aktivitet med detta namn",
      "error_unique_email" : "det finns redan en användare med denna mejl",
      "error_unique_learning_content_name" : "det finns redan ett lärinnehåll med detta namn",
      "error_unique_phone" : "det finns redan en användare med detta telefonnummer",
      "error_unique_push_notification_name" : "det finns redan ett utskick med detta namn",
      "error_unique_username" : "det finns redan en användare med detta användarnamn",
      "event" : "händelse",
      "event_log" : "logg",
      "event_reset_password" : "återställde lösenord",
      "external_url" : "extern URL",
      "failed" : "misslyckades",
      "false" : "falskt",
      "file" : "fil",
      "filename" : "filnamn",
      "file_manager" : "filhanterare",
      "file_plural" : "filer",
      "firstname" : "förnamn",
      "first_day_at_work" : "första dagen",
      "footer_learning_content" : "Lärinnehåll i sidfot",
      "forgot_password" : "glömt lösenord",
      "forgot_password_description" : "Skriv in ditt användarnamn för att återställa ditt lösenord.",
      "frontpage" : "portal",
      "frontpage_design" : "portaldesign",
      "frontpage_settings" : "portaldesign",
      "glassogram_url" : "glassogram-url",
      "home" : "hem",
      "http_400" : "Felaktig begäran - detta beror förmodligen på ett internt fel. En automatisk felrapport har skickats till vår tekniska support. Kontakta oss gärna om felet kvarstår",
      "http_401" : "Behörighet saknas - vänligen logga in igen eller kontakta oss om felet kvarstår",
      "http_403" : "Åtkomst nekad - detta beror förmodligen på ett internt fel. En automatisk felrapport har skickats till vår tekniska support. Kontakta oss gärna om felet kvarstår",
      "http_404" : "Kunde inte hitta den begärda resursen",
      "http_405" : "Felaktig metod - detta beror förmodligen på ett internt fel. En automatisk felrapport har skickats till vår tekniska support. Kontakta oss gärna om felet kvarstår",
      "http_409" : "Konflikt - detta sker vanligen när man försöker skriva över ett unikt värde för en resurs",
      "http_500" : "Internt serverfel - vänligen försök igen senare eller kontakta oss om felet kvarstår",
      "http_502" : "Felaktig gateway",
      "http_503" : "Tjänsten är inte tillgänglig för tillfället",
      "http_504" : "Gateway timeout",
      "icon" : "ikon",
      "image_plural" : "bilder",
      "library" : "bibliotek",
      "in_library" : "i bibliotek",
      "include_inactive" : "inkludera inaktiva",
      "index.html" : "dashboard",
      "information" : "information",
      "invalid_details" : "felaktigt användarnamn eller lösenord",
      "invalid_email" : "felaktig e-post",
      "invalid_phone" : "felaktigt mobilnummer",
      "invalid_token" : "felaktig återställningsnyckel",
      "invalid_url" : "Ange en giltig URL (inklusive http)",
      "invalid_youtube_id" : "Ange ett giltigt youtube id (11 tecken)",
      "key" : "nyckel",
      "last_login" : "senast inloggad",
      "lastname" : "efternamn",
      "learning_content" : "lärinnehåll",
      "learning_content_plural" : "lärinnehåll",
      "learning_contents" : "lärinnehåll",
      "library_learning_contents" : "lärinnehåll i bibliotek",
      "list" : "lista",
      "location" : "plats",
      "logged_in" : "loggade in",
      "login" : "logga in",
      "logout" : "logga ut",
      "logotype" : "logotyp",
      "max_filesize_exceeded" : "den maximala filstorleken har överskridits",
      "menu" : "meny",
      "message" : "meddelande",
      "module_plural" : "moduler",
      "name" : "namn",
      "new_password" : "nytt lösenord",
      "next" : "nästa",
      "no_actions_found" : "Inga aktiviteter funna",
      "no_learning_contents_found" : "Inga lärinnehåll funna",
      "no_courses_found" : "Inga introduktionsplaner funna",
      "no_push_notifications_found" : "Inga utskick funna",
      "no_results" : "inga resultat",
      "no_sms_credits" : "SMS-krediter saknas",
      "no_users_found" : "Inga användare funna",
      "none" : "ingen",
      "notified" : "inbjudan skickad",
      "notify_description" : "Här kan du skicka en inbjudan till användaren via mejl och/eller sms med valfritt meddelande. Ett nytt lösenord och en direktlänk till användarens profil kommer automatiskt att läggas till i slutet av meddelandet.",
      "notify_email" : "skicka mejl",
      "notify_sms" : "skicka SMS",
      "onboarding_description" : "Mobil anpassningsbar preboarding. Innehållspaket och systemstöd för en enkel, kul och effektiv introduktion av nyanställda.",
      "other" : "övrigt",
      "page" : "sida",
      "password" : "lösenord",
      "phone" : "mobilnummer",
      "phrase_plural" : "texter",
      "pixels" : "pixlar",
      "placeholder_description" : "med platshållare kan du lägga till dynamiska värden i meddelandet, exempelvis användarens namn.",
      "placeholder_plural" : "platshållare",
      "previous" : "föregående",
      "push_notification" : "utskick",
      "push_notification_plural" : "utskick",
      "push_notifications" : "utskick",
      "push_notification_not_qualified" : "Fyll i mobilnummer eller mejl för att göra utskick",
      "push_sms" : "push-SMS",
      "read_more" : "läs mer",
      "received_invitation" : "fick inbjudan",
      "received_push_notification_email" : "fick mejl-utskick",
      "received_push_notification_sms" : "fick SMS-utskick",
      "recover_password" : "Återställning lösenord introduktion.nu",
      "recover_password_message" : "<h1 style='text-align:center'>Hej!</h1><p style='text-align:center'>För att uppdatera ditt lösenord på introduktion.nu, använd följande återställningsnyckel: <strong>%token%</strong></p><p style='text-align:center; font-size:0.9em;'>Om du inte begärt att återställa ditt lösenord kan du ignorera detta meddelande.</p>",
      "remove" : "ta bort",
      "remove_from_timeline" : "ta bort från tidslinjen",
      "report_plural" : "rapporter",
      "reports" : "rapporter",
      "reset_password" : "återställ lösenord",
      "reset_password_description" : "Vi har skickat ett mejl till dig med en återställningsnyckel, klistra in den nedan för att uppdatera ditt lösenord.",
      "result" : "resultat",
      "rows" : "rader",
      "save" : "spara",
      "select" : "välj",
      "select_time" : "välj tid",
      "send" : "skicka",
      "service_plural" : "tjänster",
      "settings" : "inställningar",
      "settings_saved" : "Ändringarna har sparats.",
      "sms_credits" : "SMS-krediter",
      "sms_notification_sent" : "SMS-notifikation skickad",
      "sms_sent" : "SMS skickades.",
      "template" : "mall",
      "unavailable" : "ej tillgängligt",
      "shown" : "visat",
      "social_media" : "sociala medier",
      "specify_course" : "användaren måste vara registrerad på en introduktionsplan",
      "specify_email_address" : "ange en mejladdress",
      "specify_email_subject" : "ämnestitel får inte vara tom",
      "specify_message" : "meddelandefältet får inte vara tomt",
      "specify_phone_number" : "ange ett telefonnummer",
      "start_date" : "startdatum",
      "start_videos" : "startfilmer",
      "start_videos_description" : "Här anger du vilka filmer som visas längst upp på portalsidan, i turordning. Om du lagt till ett utskick på lärinnehållet skickas detta efter att filmen har visats första gången.",
      "state" : "stadie",
      "subject" : "ämnestitel",
      "success" : "lyckades",
      "theme" : "tema",
      "time" : "klockan",
      "timeline" : "tidslinje",
      "timeline_actions" : "aktiviteter på tidslinjen",
      "timeline_background" : "bakgrund tidslinje",
      "timestamp" : "tidpunkt",
      "token" : "återställningsnyckel",
      "true" : "sant",
      "undo" : "ångra",
      "update" : "uppdatera",
      "update_connected_users" : "uppdatera anslutna användare",
      "upload" : "ladda upp",
      "upload_quota" : "uppladdningskvot",
      "url" : "URL",
      "used_space" : "utnyttjat utrymme",
      "user" : "användare",
      "users" : "användare",
      "user_has_no_actions" : "användaren har inga kopplade aktiviteter",
      "user_has_no_learning_contents" : "användaren har inga kopplade lärinnehåll",
      "user_management" : "användarhantering",
      "user_not_found" : "kunde inte hitta någon med detta användarnamn",
      "user_has_been_notified" : "användaren fick en inbjudan",
      "user_has_not_been_notified" : "användaren har inte fått någon inbjudan",
      "user_with_email_already_exists" : "det finns redan en användare med epost: %email%",
      "user_with_username_already_exists" : "det finns redan en användare med användarnamn: %username%",
      "user_with_phone_already_exists" : "det finns redan en användare med telefonnummer: %phone%",
      "username" : "användarnamn",
      "user_plural" : "användare",
      "video" : "film",
      "viewed_learning_content" : "tog del av lärinnehåll",
      "was_created" : "skapades",
      "was_deleted" : "raderades",
      "we_look_forward_to_your_start" : "Vi ser fram emot att du ska börja!",
      "welcome" : "välkommen",
      "welcome_message" : "inbjudan",
      "your_first_day_is_in" : "Din första dag hos oss är om",
      "your_login_details_are" : "Dina inloggningsuppgifter: %username% / %password%",
      "your_profile" : "din profil",
      "your_profile_url_is" : "<p>Du kan även trycka <a href='%url%'>här</a> för att komma direkt till din profil.<br /><br /><span style='font-size: 10px;'>Fungerar inte länken? Prova att klistra in den i din browser istället:<br />%url%</span></p>",
      "Exception: Can't delete course with connected users" : "Det går inte att ta bort denna introduktionsplan eftersom den har anslutna användare.",
      "Exception: User Already Registered (http status: 409)" : "Det finns redan en användare med detta användarnamn.",
      "Exception: file_error_413" : "Ett fel inträffade: Filen är för stor! (max 1mb)",
      "Exception: mysqli_error_1451 (http-status: 403)" : "Operationen kunde inte genomföras eftersom resursen är skrivskyddad. Detta beror vanligtvis på att resursen används av en annan resurs.",
      "Exception: mysqli_error_1062 (http-status: 403)" : "Kunde inte spara objektet på grund av en unik restriktion i databasen.",
    }
  };
}