import 'package:angular2/core.dart';

@Injectable()
class PhraseService
{
  PhraseService();

  String get(String key, {Map<String, String> params : null, bool capitalize_first : true})
  {
    if (key == null) return null;
    if (key.isEmpty) return "";
    String phrase = (_phraseData.containsKey(key)) ? _phraseData[key] : key;
    if (capitalize_first) phrase = phrase[0].toUpperCase() + phrase.substring(1, phrase.length);

    if (params != null)
    {
      params.forEach((key, value)
      {
        phrase = phrase.replaceAll("%$key%", value);
      });
    }

    return phrase;
  }

  String get_multiple(List<String> phrase_keys, { Map<String, String> params : null, String separator : " ", bool capitalize_first : true})
  {
    List<String> phraseValues = new List();
    for (String key in phrase_keys)
    {
      if (_phraseData.containsKey(key)) phraseValues.add(_phraseData[key]);
      else phraseValues.add(key);
    }
    String phrase = phraseValues.join(separator);
    if (capitalize_first) phrase = phrase[0].toUpperCase() + phrase.substring(1, phrase.length);

    return phrase;
  }

  final Map<String, String> _phraseData =
  {
    "account" : "konto",
    "account_settings" : "kontoinställningar",
    "action" : "aktivitet",
    "action_plural" : "aktiviteter",
    "actions" : "aktiviteter",
    "active" : "aktiv",
    "add" : "lägg till",
    "add_many" : "lägg till flera",
    "add_action" : "lägg till aktivitet",
    "administration" : "administration",
    "advanced" : "avancerat",
    "after_first_view" : "efter första visning",
    "all" : "alla",
    "back" : "tillbaka",
    "back_to_editing" : "tillbaka till redigeringen",
    "cancel" : "avbryt",
    "change_day" : "byt dag",
    "change_time" : "byt tid",
    "choose_at_least_one" : "välj minst ett",
    "color_highlight" : "highlight",
    "color_plural" : "färger",
    "color_primary" : "primär",
    "color_secondary" : "sekundär",
    "confirm" : "bekräfta",
    "confirm_continue" : "ja, fortsätt",
    "confirm_email_sms_valid" : "Dubbelkolla att mejladressen och/eller mobilnumret stämmer:",
    "confirm_email_sms_valid_no_values" : "Du har inte angett mejladdress/mobilnummer, användaren kommer inte att få några inloggningsuppgifter skickade till sig. Är du säker på att du vill fortsätta?",
    "connected_plural" : "anslutna",
    "connected_users" : "anslutna användare",
    "contact_information" : "kontaktinformation",
    "content" : "innehåll",
    "content_title" : "innehållstitel",
    "content_type" : "innehållstyp",
    "course" : "plan",
    "course_plural" : "planer",
    "courses" : "planer",
    "created" : "skapad",
    "csv_tooltip" : "Semi-kolon mellan varje värde och radbryt mellan varje användare - mejl@mejl.com;070xxxxxxx;förnamn;efternamn",
    "custom" : "anpassad",
    "date_from" : "fr.o.m",
    "date_to" : "t.o.m.",
    "day" : "dag",
    "days_to_first_day" : "antal dagar från första dagen på jobbet",
    "delete" : "radera",
    "description" : "beskrivning",
    "design" : "design",
    "details" : "uppgifter",
    "direct_link_to_profile" : "direktlänk till profil",
    "download_template" : "hämta mall",
    "edit" : "redigera",
    "edit_action" : "redigera aktivitet",
    "edit_action_on_timeline" : "redigera aktivitet på tidslinjen",
    "email" : "mejl",
    "email_embedded_description" : "bädda in mejl-meddelandet i en standardiserad mall",
    "email_notification_sent" : "mejl-notifikation skickad",
    "email_sent" : "mejl skickades.",
    "email_template_footer" : "Har du frågor eller synpunkter? Kontakta oss gärna via mejl: support@introduktion.nu",
    "embed" : "inbäddad",
    "embedded" : "inbäddad",
    "error_occurred" : "ett fel inträffade",
    "error_unique_action_name" : "det finns redan en aktivitet med detta namn",
    "error_unique_email" : "det finns redan en användare med denna mejl",
    "error_unique_learning_content_name" : "det finns redan ett lärinnehåll med detta namn",
    "error_unique_phone" : "det finns redan en användare med detta telefonnummer",
    "error_unique_push_notification_name" : "det finns redan ett utskick med detta namn",
    "error_unique_username" : "det finns redan en användare med detta användarnamn",
    "event" : "händelse",
    "event_was_created" : "skapades",
    "event_was_deleted" : "raderades",
    "event_log" : "logg",
    "event_logged_in" : "loggade in",
    "event_viewed_learning_content" : "tog del av lärinnehåll",
    "event_received_email_push_notification" : "fick mejl-utskick",
    "event_received_sms_push_notification" : "fick SMS-utskick",
    "event_reset_password" : "återställde lösenord",
    "external_url" : "extern URL",
    "failed" : "misslyckades",
    "file" : "fil",
    "filename" : "filnamn",
    "file_manager" : "filhanterare",
    "file_plural" : "filer",
    "firstname" : "förnamn",
    "first_day_at_work" : "första dagen",
    "footer_learning_content" : "Lärinnehåll i sidfot",
    "footer_learning_content_description" : "Välj vilket lärinnehåll i biblioteket som ska visas i sidfoten.",
    "forgot_password" : "glömt lösenord",
    "forgot_password_description" : "Skriv in ditt användarnamn för att återställa ditt lösenord.",
    "frontpage" : "portal",
    "frontpage_design" : "portaldesign",
    "frontpage_settings" : "portaldesign",
    "icon" : "ikon",
    "image_plural" : "bilder",
    "in_library" : "i bibliotek",
    "include_inactive" : "inkludera inaktiva",
    "index.html" : "dashboard",
    "information" : "information",
    "invalid_details" : "felaktigt användarnamn eller lösenord",
    "invalid_email" : "felaktig e-post",
    "invalid_phone" : "felaktigt mobilnummer",
    "invalid_url" : "Ange en giltig URL (inklusive http)",
    "invalid_youtube_id" : "Ange ett giltigt youtube video id (11 tecken)",
    "key" : "nyckel",
    "last_login" : "senast inloggad",
    "lastname" : "efternamn",
    "learning_content" : "lärinnehåll",
    "learning_content_plural" : "lärinnehåll",
    "learning_contents" : "lärinnehåll",
    "library_learning_contents" : "lärinnehåll i bibliotek",
    "list" : "lista",
    "location" : "plats",
    "login" : "logga in",
    "logout" : "logga ut",
    "logotype" : "logotyp",
    "max_filesize_exceeded" : "den maximala filstorleken har överskridits",
    "menu" : "meny",
    "message" : "meddelande",
    "module_plural" : "moduler",
    "name" : "namn",
    "new_password" : "nytt lösenord",
    "next" : "nästa",
    "no_actions_found" : "Inga aktiviteter funna",
    "no_learning_contents_found" : "Inga lärinnehåll funna",
    "no_courses_found" : "Inga planer funna",
    "no_push_notifications_found" : "Inga utskick funna",
    "no_results" : "inga resultat",
    "no_sms_credits" : "SMS-krediter saknas",
    "no_users_found" : "Inga användare funna",
    "none" : "ingen",
    "notified" : "inbjudan skickad",
    "notify_email" : "skicka mejl",
    "notify_sms" : "skicka SMS",
    "other" : "övrigt",
    "page" : "sida",
    "password" : "lösenord",
    "phone" : "mobilnummer",
    "phrase_plural" : "texter",
    "pixels" : "pixlar",
    "placeholder_description" : "med platshållare kan du lägga till dynamiska värden i meddelandet, exempelvis användarens namn.",
    "placeholder_plural" : "platshållare",
    "previous" : "föregående",
    "push_notification" : "utskick",
    "push_notification_plural" : "utskick",
    "push_notifications" : "utskick",
    "push_notification_not_qualified" : "Fyll i mobilnummer eller mejl för att göra utskick",
    "push_sms" : "push-SMS",
    "recover_password" : "Återställning lösenord introduktion.nu",
    "recover_password_message" : "<h1 style='text-align:center'>Hej!</h1><p style='text-align:center'>För att uppdatera ditt lösenord på introduktion.nu, använd följande återställningsnyckel: <strong>%token%</strong></p><p style='text-align:center; font-size:0.9em;'>Om du inte begärt att återställa ditt lösenord kan du ignorera detta meddelande.</p>",
    "remove" : "ta bort",
    "remove_from_timeline" : "ta bort från tidslinjen",
    "report_plural" : "rapporter",
    "reports" : "rapporter",
    "reset_password" : "återställ lösenord",
    "reset_password_description" : "Vi har skickat ett mejl till dig med en återställningsnyckel, klistra in den nedan för att uppdatera ditt lösenord.",
    "result" : "resultat",
    "save" : "spara",
    "select" : "välj",
    "select_time" : "välj tid",
    "send" : "skicka",
    "send_voucher" : "skicka glassogram-sms efter första videon",
    "settings" : "inställningar",
    "settings_saved" : "Ändringarna har sparats.",
    "sms_credits" : "SMS-krediter",
    "sms_notification_sent" : "SMS-notifikation skickad",
    "sms_sent" : "SMS skickades.",
    "template" : "mall",
    "unavailable" : "ej tillgängligt",
    "shown" : "visat",
    "social_media" : "sociala medier",
    "specify_course" : "användaren måste vara registrerad på en plan",
    "specify_email_address" : "ange en mejladdress",
    "specify_email_subject" : "ämnestitel får inte vara tom",
    "specify_message" : "meddelandefältet får inte vara tomt",
    "specify_phone_number" : "ange ett telefonnummer",
    "start_date" : "startdatum",
    "start_videos" : "startfilmer",
    "start_videos_description" : "Välj vilket lärinnehåll som ska visas längs upp på framsidan, i turordning.",
    "state" : "stadie",
    "subject" : "ämnestitel",
    "success" : "lyckades",
    "theme" : "tema",
    "time" : "klockan",
    "timeline" : "tidslinje",
    "timeline_actions" : "aktiviteter på tidslinjen",
    "timeline_background" : "bakgrund tidslinje",
    "undo" : "ångra",
    "update" : "uppdatera",
    "update_connected_users" : "uppdatera anslutna användare",
    "upload" : "ladda upp",
    "upload_quota" : "uppladdningskvot",
    "url" : "URL",
    "used_space" : "utnyttjat utrymme",
    "user" : "användare",
    "users" : "användare",
    "user_has_no_actions" : "användaren har inga kopplade aktiviteter",
    "user_has_no_learning_contents" : "användaren har inga kopplade lärinnehåll",
    "user_management" : "användarhantering",
    "user_not_found" : "kunde inte hitta någon med detta användarnamn",
    "user_has_been_notified" : "användaren fick en inbjudan",
    "user_has_not_been_notified" : "användaren har inte fått någon inbjudan",
    "user_with_email_already_exists" : "det finns redan en användare med epost: %email%",
    "user_with_username_already_exists" : "det finns redan en användare med användarnamn: %username%",
    "user_with_phone_already_exists" : "det finns redan en användare med telefonnummer: %phone%",
    "username" : "användarnamn",
    "user_plural" : "användare",
    "welcome_message" : "inbjudan",
    "Exception: Can't delete course with connected users" : "Det går inte att ta bort denna plan eftersom den har anslutna användare.",
    "Exception: User Already Registered (http status: 409)" : "Det finns redan en användare med detta användarnamn.",
    "Exception: file_error_413" : "Ett fel inträffade: Filen är för stor! (max 1mb)",
    "Exception: mysqli_error_1451 (http-status: 403)" : "Operationen kunde inte genomföras eftersom objektet är skrivskyddat.",
    "Exception: mysqli_error_1062 (http-status: 403)" : "Kunde inte spara objektet på grund av en unik restriktion i databasen.",
  };
}